import {faker} from '@faker-js/faker';
import img1 from '@assets/products/electronics/3.webp';
import img2 from '@assets/products/electronics/7.webp';
import img3 from '@assets/products/food/3.webp';
import img4 from '@assets/products/services/1.webp';
import img5 from '@assets/products/fashion/4.webp';
import img6 from '@assets/products/food/18.webp';
import img7 from '@assets/products/electronics/16.webp';
import img8 from '@assets/products/electronics/24.webp';
import img9 from '@assets/products/electronics/1.webp';
import img10 from '@assets/products/food/12.webp';
import img11 from '@assets/products/food/13.webp';
import img12 from '@assets/products/fashion/10.webp';
import img13 from '@assets/products/services/1.webp';
import img14 from '@assets/products/fashion/2.webp';
import img15 from '@assets/products/electronics/2.webp';
import img16 from '@assets/products/electronics/8.webp';

const products_management = [
    {
        product_sku: 'TR-001',
        product_thumb_small: img1,
        product_name: 'Xiaomi WiFI Repeater Pro',
        product_quantity: 120,
        product_price: 254,
        product_type: 'electronics',
        type: 'simple',
        statistics: 'best seller',
        tags: ['top rated', 'best seller', 'phone'],
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-002',
        product_thumb_small: img2,
        product_name: 'Logi Wireless Keyboard',
        product_quantity: 3,
        product_price: 117,
        product_type: 'electronics',
        type: 'variable',
        statistics: 'top rated',
        tags: [],
        product_ratings: 4,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-003',
        product_thumb_small: img3,
        product_name: 'Spry Chewing Gum 100 Pack Mint',
        product_quantity: 0,
        product_price: 12.30,
        product_type: 'food & drinks',
        type: 'grouped',
        statistics: 'new in',
        tags: [],
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-004',
        product_thumb_small: img4,
        product_name: 'Delivery box package',
        product_price: 9.99,
        product_type: 'services',
        type: 'service',
        statistics: 'featured',
        tags: ['top rated', 'best seller', 'phone'],
        product_ratings: 3,
        createdAt: faker.date.past(),
        status: 'trash',
    },
    {
        product_sku: 'TR-005',
        product_thumb_small: img5,
        product_name: 'Traum Signature Graffiti Hat',
        product_quantity: 345,
        product_price: 120.35,
        product_type: 'fashion',
        type: 'simple',
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'draft',
    },
    {
        product_sku: 'TR-006',
        product_thumb_small: img6,
        product_name: 'Ferrero Rocher 16 Pack Special',
        product_quantity: 0,
        product_price: 504,
        product_type: 'food & drinks',
        type: 'simple',
        tags: ['food', 'sweets', 'gifts'],
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'draft',
    },
    {
        product_sku: 'TR-007',
        product_thumb_small: img7,
        product_name: 'ELITE LCD Display Liquid CPU Cooler',
        product_quantity: 0,
        product_price: 99.99,
        product_type: 'electronics',
        type: 'simple',
        statistics: 'best seller',
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'draft',
    },
    {
        product_sku: 'TR-008',
        product_thumb_small: img8,
        product_name: 'Acer GVB708 15" Laptop Silver',
        product_quantity: 2,
        product_price: 117,
        product_type: 'electronics',
        type: 'variable',
        statistics: 'top rated',
        tags: [],
        product_ratings: 4,
        createdAt: faker.date.past(),
        status: 'trash'
    },
    {
        product_sku: 'TR-009',
        product_thumb_small: img9,
        product_name: 'Oculus Quest 2 VR Headset',
        product_quantity: 9,
        product_price: 299,
        product_type: 'electronics',
        type: 'variable',
        statistics: 'top rated',
        tags: ['VR', 'Meta', 'Oculus', 'Gaming'],
        product_ratings: 4,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-010',
        product_thumb_small: img10,
        product_name: 'Pergale Picks Strawberry 1kg',
        product_quantity: 354,
        product_price: 12.30,
        product_type: 'food & drinks',
        type: 'grouped',
        statistics: 'new in',
        tags: [],
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-011',
        product_thumb_small: img11,
        product_name: 'Skittles Fruitty Family Pack',
        product_quantity: 0,
        product_price: 9.99,
        product_type: 'food & drinks',
        type: 'grouped',
        statistics: 'featured',
        tags: ['top rated', 'best seller', 'sweets'],
        product_ratings: 3,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-012',
        product_thumb_small: img12,
        product_name: 'Yumi Sunny Yellow City Backpack',
        product_quantity: 98,
        product_price: 120.35,
        product_type: 'fashion',
        type: 'simple',
        product_ratings: 0,
        createdAt: faker.date.past(),
        status: 'draft',
    },
    {
        product_sku: 'TR-013',
        product_thumb_small: img13,
        product_name: 'UPS Express Shipping',
        product_price: 9.99,
        product_type: 'services',
        type: 'service',
        statistics: 'featured',
        tags: [],
        product_ratings: 3,
        createdAt: faker.date.past(),
        status: 'trash',
    },
    {
        product_sku: 'TR-014',
        product_thumb_small: img14,
        product_name: 'SNSY Fancy Red Woman Sandals',
        product_quantity: 0,
        product_price: 58.72,
        product_type: 'fashion',
        type: 'simple',
        tags: ['top rated', 'best seller', 'shoes'],
        product_ratings: 3,
        createdAt: faker.date.past(),
        status: 'draft',
    },
    {
        product_sku: 'TR-015',
        product_thumb_small: img15,
        product_name: 'Nintendo Switch Gaming Console',
        product_quantity: 874,
        product_price: 299,
        product_type: 'electronics',
        type: 'variable',
        statistics: 'top rated',
        tags: ['Nintendo', 'Gaming', 'Console'],
        product_ratings: 4,
        createdAt: faker.date.past(),
        status: 'publish',
    },
    {
        product_sku: 'TR-016',
        product_thumb_small: img16,
        product_name: 'ARTLINE Overlord Gaming PC',
        product_quantity: 7,
        product_price: 497,
        product_type: 'electronics',
        type: 'variable',
        statistics: 'top rated',
        tags: ['Gaming', 'PC', 'Computer'],
        product_ratings: 4,
        createdAt: faker.date.past(),
        status: 'trash',
    }
]

export default products_management